### PR TITLE
fix 2500 sample sheet issues

### PR DESCRIPTION
**Pull request by barrystokman**
This PR adds conversion of old 2500 sample sheets so demuxing and cgstats works on Hasta.

**How to prepare for test**:
- [x] ssh to hasta
- [x] install on stage:
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [x] `rsync -av /home/proj/production/flowcells/2500/runs/140818_D00410_0089_AH9M8MADXX /home/proj/stage/flowcells/2500/runs/`
- [x] make sure all run dirs in `/home/proj/stage/flowcells/2500/runs/` have a `demuxstarted.txt` EXCEPT `140818_D00410_0089_AH9M8MADXX`
- [x] run `bash /home/proj/stage/bin/git/demultiplexing/scripts/2500/stage/checkfornewrun.bash /home/proj/stage/flowcells/2500/runs/ /home/proj/stage/demultiplexed-runs/ &>> /home/proj/stage/logs/checkfornewrun.2500.log`

**Expected test outcome**:
- [x] check that demultiplexing has finished and started correctly
- [x] check `/home/proj/stage/logs/checkfornewrun.2500.log` and `/home/proj/stage/demultiplexed-runs/140818_D00410_0089_AH9M8MADXX/projectlog.*.log` for errors and inconsistencies
- [ ] Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [x] tests executed by @barrystokman 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by barrystokman** [comment]
image

**Comment by barrystokman** [comment]
Only undetermined fastqs:
image

**Comment by barrystokman** [comment]
`demux sheet convert /home/proj/stage/flowcells/2500/runs/140818_D00410_0089_AH9M8MADXX/SampleSheet.csv `:
image

Preconditions `cgstats select H9M8MADXX`:
image

Post demux `cgstats select H9M8MADXX`:
image

Comparison post demux `cgstats select H9M8MADXX` in `P_main`:
image

**Review by karlnyr — APPROVED** [review]
thank god for snapshots, great cleanup! 💯

**Comment by barrystokman** [comment]
Bumped:
image

**Pull request merged**
