### PR TITLE
Fix/demux mail

### PR DESCRIPTION
**Pull request by barrystokman**
This PR adds/fixes ...

**How to prepare for test**:
- [ ] ssh to hasta
- [ ] install on stage:
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh [THIS-BRANCH-NAME]`

**How to test**:
- [ ] login to ...
- [ ] do ...

**Expected test outcome**:
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by karlnyr — APPROVED** [review]
Such a rookie mistake by me (with unbound variables), this should work just fine 👍

**Comment by karlnyr** [comment]
We should not launch this into prod before both demultiplexing are done, probably Wednesday?

**Comment by karlnyr** [comment]
@barrystokman Should we close this? This issue has already been solved by another pr.

**Comment by barrystokman** [comment]
Yes, closing this.

**Pull request closed without merging**
