### PR TITLE
iseq sample sheet: index2 is reverse complement of index2 found in LIMS

### PR DESCRIPTION
**Pull request by barrystokman**
This PR makes sure the iSeq sample sheet is formatted correctly.

This PR solves https://github.com/Clinical-Genomics/demultiplexing/issues/90

**How to test**:
1. install on stage of thalamus: `bash /home/hiseq.clinical/servers/resources/clinical-preproc.scilifelab.se/update-demux-stage.sh iseq-sample-sheet`
1. activate stage: `source activate stage`
1. run following command: `demux sheet fetch -a iseq -p --longest BPC29611-3324`

**Expected outcome**:
The sample sheet should be printed to the terminal, and index2 of Sample_ID `ACC5726A1` should read `ACACTAAGGT` instead of `ACCTTAGTGT`

**Review:**
- [x] code approved by @ingkebil 
- [x] tests executed by @barrystokman 
- [x] "Merge and deploy" approved by @ingkebil 
Thanks for filling in who performed the code review and the test!

This is minor **version bump** because it's a backwards compatible change

### CODE REVIEW

**Comment by ingkebil** [comment]
Oh, just saw this was still a draft. Well, so far so good!

**Comment by barrystokman** [comment]
image

:heavy_check_mark:

**Comment by ingkebil** [comment]
Approved!

**Comment by ingkebil** [comment]
hehe, nice catch :)

**Comment by barrystokman** [comment]
it was only there for 5 months haha

Kind regards/med vänliga hälsningar,

*Barry Stokman*
Scrum Master/Developer
Clinical Genomics | SciLifeLab

**Comment by barrystokman** [comment]
By request of @emiliaol and @patrikgrenfeldt I added fcid to the sample sheet, tests are still ok:
image

**Pull request merged**
