### PR TITLE
fix weirdness caused by bumpversion typo

### PR DESCRIPTION
**Pull request by barrystokman**
This PR fixes corrupted `pyproject.toml`, causing error during deployment.

**How to prepare for test**:
- [x] Install on stage.

**Expected test outcome
- [x] deployment on stage finishes without errors.

**Review:**
- [ ] code approved by
- [x] tests executed by @barrystokman 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by barrystokman** [comment]
image

**Comment by barrystokman** [comment]
Bumped & deployed on hasta!
image

image

**Comment by barrystokman** [comment]
For reference:

Before `bumpversion`:

```
[tool.poetry]
name = "demux"
version = "5.5.3"
description = "Application for demultiplexing sequence data"
authors = ["henrikstranneheim <henrik.stranneheim@scilifelab.se>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^5.3.1"
psutil = "^5.7.3"
"path.py" = "^12.5.0"
click = "^6.7.0"
cglims = "^1.3.4"
six = "^1.15.0"
importlib-metadata = "^3.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
coveralls = "^2.2.0"

[tool.poetry.scripts]
demux = "demux.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

after `bumpversion pathc` (note typo):

```
⏚ [barry:~/bumpversion/demultiplexing] [base] master ± bumpversion pathc
fatal: tag '5.5.3' already exists
Traceback (most recent call last):
  File "/home/barry/anaconda3/bin/bumpversion", line 10, in <module>
    sys.exit(main())
  File "/home/barry/anaconda3/lib/python3.7/site-packages/bumpversion/__init__.py", line 1004, in main
    vcs.tag(tag_name)
  File "/home/barry/anaconda3/lib/python3.7/site-packages/bumpversion/__init__.py", line 150, in tag
    subprocess.check_output(["git", "tag", name])
  File "/home/barry/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/barry/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'tag', '5.5.3']' returned non-zero exit status 128.
```

````
[tool.poetry]
name = "demux"
version = "version = "5.5.3""  <-----!!!!!
description = "Application for demultiplexing sequence data"
authors = ["henrikstranneheim <henrik.stranneheim@scilifelab.se>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^5.3.1"
psutil = "^5.7.3"
"path.py" = "^12.5.0"
click = "^6.7.0"
cglims = "^1.3.4"
six = "^1.15.0"
importlib-metadata = "^3.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
coveralls = "^2.2.0"

[tool.poetry.scripts]
demux = "demux.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Pull request merged**
