### PR TITLE
Version check for updates to Novaseq versions

### PR DESCRIPTION
**Pull request by karlnyr**
Control versions and kit versions were previously checked to be a specific one. However, after discussions with @AnnaZetterlund and @barrystokman we came to the conclusion that we should check if these are at least of the same or newer version.

**How to prepare for test**:
- [x] ssh to hasta
- [x] activate stage
- [x] install on stage:
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh control_and_reagent_version_fix`

**How to test**:
- [x] activate stage
- [x] Connect to LIMS prod to fetch FC info
- [x] change RunParameters.xml to:
    - [x] Control software version: `1.7.5`
    - [x] Reagent kit version: `3`
- [x] do `demux -c /home/karl.nyren/demux-stage.yaml sheet fetch --application nova --pad --longest H5GL3DRXY > /home/proj/stage/flowcells/novaseq/runs/210421_A00689_0257_AH5GL3DRXY/1.7.5_3_SampleSheet.csv` 
- [x] Ensure reverse complement i applied
- [x] change RunParameters.xml to:
    - [x] Control software version: `1.6.5`
    - [x] Reagent kit version: `3`
- [x] do `demux -c /home/karl.nyren/demux-stage.yaml sheet fetch --application nova --pad --longest H5GL3DRXY > /home/proj/stage/flowcells/novaseq/runs/210421_A00689_0257_AH5GL3DRXY/1.6.5_3_SampleSheet.csv`
- [x] Ensure reverse complement is not applied
- [x] change RunParameters.xml to:
    - [x] Control software version: `1.7.5`
    - [x] Reagent kit version: `1`
- [x] do `demux -c /home/karl.nyren/demux-stage.yaml sheet fetch --application nova --pad --longest H5GL3DRXY > /home/proj/stage/flowcells/novaseq/runs/210421_A00689_0257_AH5GL3DRXY/1.7.5_1_SampleSheet.csv` 
- [x] Ensure reverse complement is not applied

**Expected test outcome**:
- [ ] check that:
    - [x] There is a difference in all rows of a non-reverse complemented index SampleSheet.csv and a reverse complemented one
    - [x] There is no difference of a non-reverse complemented index SampleSheet.csv and another non-reverse complemented one
- [x] Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @barrystokman 
- [x] tests executed by @karlnyr 
- [x] "Merge and deploy" approved by @barrystokman 
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by karlnyr** [comment]
This is not ready for review. Obviously wont work

**Comment by karlnyr** [comment]
Installing on stage:
image

**Review by barrystokman — APPROVED** [review]
Code approved!

**Comment by karlnyr** [comment]
NCVS 1.7.5, KIT 3:
```shell
[0|0|6] [karl.nyren@hasta:/home … eq/runs/210421_A00689_0257_AH5GL3DRXY] [S_main] $ diff 1.7.5_3_SampleSheet.csv not_rev_comp_SampleSheet.csv
3,94c3,94
< H5GL3DRXY,1,ACC7864A1,hg19,AATCGTTA,ACGTTATT,2021-08275-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A2,hg19,AATCGGCG,TCAATATT,2021-08276-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A3,hg19,AATCCGTT,AGCATATT,2021-08320-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A4,hg19,AAGATACA,CAGATATT,2021-08321-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A5,hg19,AAGACGAA,AATCTATT,2021-08322-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A6,hg19,AAGTAAGT,GGACTATT,2021-08324-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A7,hg19,AAGTTATC,TTGCTATT,2021-08339-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A8,hg19,AAGTTGGA,CCTGTATT,2021-08341-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A9,hg19,GTCTACAT,TTCAAGAA,2021-08343-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A10,hg19,TTCGCCGA,CGGTATAC,2021-08358-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A11,hg19,TGCGTACA,TATGAGAA,2021-08359-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A12,hg19,GTCGCTGT,TGATATAA,2021-08361-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A13,hg19,TTATTATG,TGCGCTAA,2021-08385-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A14,hg19,TGACTGAA,ACGTCTAA,2021-08386-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A15,hg19,GTACAGCT,ACCGATCA,2021-08398-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A16,hg19,GGACAACG,GGCCATCA,2021-08414-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A17,hg19,CGCTGCTC,GATCTGCC,2021-08415-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A18,hg19,CTGGCCTC,GTTGGATC,2021-08476-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A19,hg19,GAATCAAT,ATCACAGA,2021-08477-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A20,hg19,TCGGATGT,ATCCGCAG,2021-08478-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A21,hg19,CGCTATTA,ACGGCCGC,2021-08479-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A22,hg19,AAGACTGT,TAGTCCAC,2021-08480-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A23,hg19,CAACTGCT,ATACTACT,2021-08481-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A24,hg19,GATCAACA,TAACATAG,2021-08482-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A25,hg19,GAACTTAT,GCGTATCT,2021-08483-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A26,hg19,TGAGTCAG,AAGTTCGG,2021-08484-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A27,hg19,CGAGCCGG,CAAGCCGC,2021-08485-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A28,hg19,TCTATCAG,GGTTACTG,2021-08535-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A29,hg19,CAATGATG,CGTCCGTG,2021-08536-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A30,hg19,CATGATGA,CCTCTAAC,2021-08537-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A31,hg19,CAGACCAC,GCCGAAGC,2021-08538-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A32,hg19,CGAAGGAC,GCGTCAAC,2021-08539-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A33,hg19,CGTATTGG,AAGATACC,2021-08542-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A34,hg19,GAATGCTC,TGTTAGAC,2021-08548-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A35,hg19,CGATTATC,ATCAACTC,2021-08563-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A36,hg19,CGGTGGTA,TACTAGGC,2021-08565-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A37,hg19,CACAGTAA,CTCTAGTG,2021-08566-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A38,hg19,TGACTACT,CTGTAAGG,2021-08567-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A39,hg19,TTCTGGTG,ACCACTGG,2021-08568-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A40,hg19,GATGCCGG,TCGTAGAT,2021-08576-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A41,hg19,GAAGCACA,GCCAGAGG,2021-08577-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A42,hg19,GAATATCC,ATGGCGTC,2021-08578-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A43,hg19,TCGAAGCT,CTCAGTGC,2021-08605-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A44,hg19,TCACCAAT,GCGCCGTG,2021-08606-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A45,hg19,TGGTCATT,CCATCTGC,2021-08663-05,N,R1,script,193901
< H5GL3DRXY,1,ACC7864A46,hg19,CAGAAGAT,CAATGTAC,2021-08665-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A1,hg19,AATCGTTA,ACGTTATT,2021-08275-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A2,hg19,AATCGGCG,TCAATATT,2021-08276-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A3,hg19,AATCCGTT,AGCATATT,2021-08320-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A4,hg19,AAGATACA,CAGATATT,2021-08321-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A5,hg19,AAGACGAA,AATCTATT,2021-08322-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A6,hg19,AAGTAAGT,GGACTATT,2021-08324-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A7,hg19,AAGTTATC,TTGCTATT,2021-08339-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A8,hg19,AAGTTGGA,CCTGTATT,2021-08341-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A9,hg19,GTCTACAT,TTCAAGAA,2021-08343-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A10,hg19,TTCGCCGA,CGGTATAC,2021-08358-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A11,hg19,TGCGTACA,TATGAGAA,2021-08359-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A12,hg19,GTCGCTGT,TGATATAA,2021-08361-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A13,hg19,TTATTATG,TGCGCTAA,2021-08385-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A14,hg19,TGACTGAA,ACGTCTAA,2021-08386-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A15,hg19,GTACAGCT,ACCGATCA,2021-08398-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A16,hg19,GGACAACG,GGCCATCA,2021-08414-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A17,hg19,CGCTGCTC,GATCTGCC,2021-08415-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A18,hg19,CTGGCCTC,GTTGGATC,2021-08476-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A19,hg19,GAATCAAT,ATCACAGA,2021-08477-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A20,hg19,TCGGATGT,ATCCGCAG,2021-08478-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A21,hg19,CGCTATTA,ACGGCCGC,2021-08479-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A22,hg19,AAGACTGT,TAGTCCAC,2021-08480-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A23,hg19,CAACTGCT,ATACTACT,2021-08481-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A24,hg19,GATCAACA,TAACATAG,2021-08482-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A25,hg19,GAACTTAT,GCGTATCT,2021-08483-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A26,hg19,TGAGTCAG,AAGTTCGG,2021-08484-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A27,hg19,CGAGCCGG,CAAGCCGC,2021-08485-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A28,hg19,TCTATCAG,GGTTACTG,2021-08535-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A29,hg19,CAATGATG,CGTCCGTG,2021-08536-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A30,hg19,CATGATGA,CCTCTAAC,2021-08537-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A31,hg19,CAGACCAC,GCCGAAGC,2021-08538-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A32,hg19,CGAAGGAC,GCGTCAAC,2021-08539-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A33,hg19,CGTATTGG,AAGATACC,2021-08542-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A34,hg19,GAATGCTC,TGTTAGAC,2021-08548-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A35,hg19,CGATTATC,ATCAACTC,2021-08563-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A36,hg19,CGGTGGTA,TACTAGGC,2021-08565-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A37,hg19,CACAGTAA,CTCTAGTG,2021-08566-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A38,hg19,TGACTACT,CTGTAAGG,2021-08567-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A39,hg19,TTCTGGTG,ACCACTGG,2021-08568-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A40,hg19,GATGCCGG,TCGTAGAT,2021-08576-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A41,hg19,GAAGCACA,GCCAGAGG,2021-08577-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A42,hg19,GAATATCC,ATGGCGTC,2021-08578-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A43,hg19,TCGAAGCT,CTCAGTGC,2021-08605-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A44,hg19,TCACCAAT,GCGCCGTG,2021-08606-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A45,hg19,TGGTCATT,CCATCTGC,2021-08663-05,N,R1,script,193901
< H5GL3DRXY,2,ACC7864A46,hg19,CAGAAGAT,CAATGTAC,2021-08665-05,N,R1,script,193901
---
> H5GL3DRXY,1,ACC7864A1,hg19,AATCGTTA,AATAACGT,2021-08275-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A2,hg19,AATCGGCG,AATATTGA,2021-08276-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A3,hg19,AATCCGTT,AATATGCT,2021-08320-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A4,hg19,AAGATACA,AATATCTG,2021-08321-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A5,hg19,AAGACGAA,AATAGATT,2021-08322-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A6,hg19,AAGTAAGT,AATAGTCC,2021-08324-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A7,hg19,AAGTTATC,AATAGCAA,2021-08339-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A8,hg19,AAGTTGGA,AATACAGG,2021-08341-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A9,hg19,GTCTACAT,TTCTTGAA,2021-08343-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A10,hg19,TTCGCCGA,GTATACCG,2021-08358-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A11,hg19,TGCGTACA,TTCTCATA,2021-08359-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A12,hg19,GTCGCTGT,TTATATCA,2021-08361-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A13,hg19,TTATTATG,TTAGCGCA,2021-08385-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A14,hg19,TGACTGAA,TTAGACGT,2021-08386-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A15,hg19,GTACAGCT,TGATCGGT,2021-08398-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A16,hg19,GGACAACG,TGATGGCC,2021-08414-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A17,hg19,CGCTGCTC,GGCAGATC,2021-08415-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A18,hg19,CTGGCCTC,GATCCAAC,2021-08476-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A19,hg19,GAATCAAT,TCTGTGAT,2021-08477-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A20,hg19,TCGGATGT,CTGCGGAT,2021-08478-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A21,hg19,CGCTATTA,GCGGCCGT,2021-08479-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A22,hg19,AAGACTGT,GTGGACTA,2021-08480-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A23,hg19,CAACTGCT,AGTAGTAT,2021-08481-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A24,hg19,GATCAACA,CTATGTTA,2021-08482-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A25,hg19,GAACTTAT,AGATACGC,2021-08483-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A26,hg19,TGAGTCAG,CCGAACTT,2021-08484-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A27,hg19,CGAGCCGG,GCGGCTTG,2021-08485-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A28,hg19,TCTATCAG,CAGTAACC,2021-08535-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A29,hg19,CAATGATG,CACGGACG,2021-08536-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A30,hg19,CATGATGA,GTTAGAGG,2021-08537-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A31,hg19,CAGACCAC,GCTTCGGC,2021-08538-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A32,hg19,CGAAGGAC,GTTGACGC,2021-08539-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A33,hg19,CGTATTGG,GGTATCTT,2021-08542-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A34,hg19,GAATGCTC,GTCTAACA,2021-08548-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A35,hg19,CGATTATC,GAGTTGAT,2021-08563-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A36,hg19,CGGTGGTA,GCCTAGTA,2021-08565-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A37,hg19,CACAGTAA,CACTAGAG,2021-08566-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A38,hg19,TGACTACT,CCTTACAG,2021-08567-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A39,hg19,TTCTGGTG,CCAGTGGT,2021-08568-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A40,hg19,GATGCCGG,ATCTACGA,2021-08576-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A41,hg19,GAAGCACA,CCTCTGGC,2021-08577-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A42,hg19,GAATATCC,GACGCCAT,2021-08578-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A43,hg19,TCGAAGCT,GCACTGAG,2021-08605-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A44,hg19,TCACCAAT,CACGGCGC,2021-08606-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A45,hg19,TGGTCATT,GCAGATGG,2021-08663-05,N,R1,script,193901
> H5GL3DRXY,1,ACC7864A46,hg19,CAGAAGAT,GTACATTG,2021-08665-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A1,hg19,AATCGTTA,AATAACGT,2021-08275-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A2,hg19,AATCGGCG,AATATTGA,2021-08276-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A3,hg19,AATCCGTT,AATATGCT,2021-08320-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A4,hg19,AAGATACA,AATATCTG,2021-08321-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A5,hg19,AAGACGAA,AATAGATT,2021-08322-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A6,hg19,AAGTAAGT,AATAGTCC,2021-08324-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A7,hg19,AAGTTATC,AATAGCAA,2021-08339-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A8,hg19,AAGTTGGA,AATACAGG,2021-08341-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A9,hg19,GTCTACAT,TTCTTGAA,2021-08343-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A10,hg19,TTCGCCGA,GTATACCG,2021-08358-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A11,hg19,TGCGTACA,TTCTCATA,2021-08359-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A12,hg19,GTCGCTGT,TTATATCA,2021-08361-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A13,hg19,TTATTATG,TTAGCGCA,2021-08385-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A14,hg19,TGACTGAA,TTAGACGT,2021-08386-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A15,hg19,GTACAGCT,TGATCGGT,2021-08398-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A16,hg19,GGACAACG,TGATGGCC,2021-08414-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A17,hg19,CGCTGCTC,GGCAGATC,2021-08415-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A18,hg19,CTGGCCTC,GATCCAAC,2021-08476-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A19,hg19,GAATCAAT,TCTGTGAT,2021-08477-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A20,hg19,TCGGATGT,CTGCGGAT,2021-08478-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A21,hg19,CGCTATTA,GCGGCCGT,2021-08479-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A22,hg19,AAGACTGT,GTGGACTA,2021-08480-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A23,hg19,CAACTGCT,AGTAGTAT,2021-08481-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A24,hg19,GATCAACA,CTATGTTA,2021-08482-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A25,hg19,GAACTTAT,AGATACGC,2021-08483-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A26,hg19,TGAGTCAG,CCGAACTT,2021-08484-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A27,hg19,CGAGCCGG,GCGGCTTG,2021-08485-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A28,hg19,TCTATCAG,CAGTAACC,2021-08535-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A29,hg19,CAATGATG,CACGGACG,2021-08536-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A30,hg19,CATGATGA,GTTAGAGG,2021-08537-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A31,hg19,CAGACCAC,GCTTCGGC,2021-08538-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A32,hg19,CGAAGGAC,GTTGACGC,2021-08539-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A33,hg19,CGTATTGG,GGTATCTT,2021-08542-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A34,hg19,GAATGCTC,GTCTAACA,2021-08548-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A35,hg19,CGATTATC,GAGTTGAT,2021-08563-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A36,hg19,CGGTGGTA,GCCTAGTA,2021-08565-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A37,hg19,CACAGTAA,CACTAGAG,2021-08566-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A38,hg19,TGACTACT,CCTTACAG,2021-08567-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A39,hg19,TTCTGGTG,CCAGTGGT,2021-08568-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A40,hg19,GATGCCGG,ATCTACGA,2021-08576-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A41,hg19,GAAGCACA,CCTCTGGC,2021-08577-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A42,hg19,GAATATCC,GACGCCAT,2021-08578-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A43,hg19,TCGAAGCT,GCACTGAG,2021-08605-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A44,hg19,TCACCAAT,CACGGCGC,2021-08606-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A45,hg19,TGGTCATT,GCAGATGG,2021-08663-05,N,R1,script,193901
> H5GL3DRXY,2,ACC7864A46,hg19,CAGAAGAT,GTACATTG,2021-08665-05,N,R1,script,193901
```

NVSC 1.6.5, KIT 3:
```shell
[0|0|6] [karl.nyren@hasta:/home … eq/runs/210421_A00689_0257_AH5GL3DRXY] [S_main] 9s $ diff 1.6.5_3_SampleSheet.csv not_rev_comp_SampleSheet.csv
[0|0|6] [karl.nyren@hasta:/home … eq/runs/210421_A00689_0257_AH5GL3DRXY] [S_main] $
```

NVSC 1.7.5, KIT 1:
```
[0|0|6] θ66° [karl.nyren@hasta:/home … eq/runs/210421_A00689_0257_AH5GL3DRXY] [S_main] $ diff 1.7.5_1_SampleSheet.csv not_rev_comp_SampleSheet.csv
[0|0|6] θ67° [karl.nyren@hasta:/home … eq/runs/210421_A00689_0257_AH5GL3DRXY] [S_main] $
```

In all cases the RunParameter.xml were altered so that the versions were properly checked. No output from `diff`  means that all the rows are identical to the not_rev_comp_SampleSheet.csv

**Comment by karlnyr** [comment]
Installed on prod:
image

**Pull request merged**
