### PR TITLE
Automatic demultiplexing of iseq runs

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
This PR adds demuliplexing support for iSeq

**How to setup**:
1. install on stage of thalamus: `bash servers/resources/clinical-preproc.scilifelab.se/update-demux-stage.sh Automatic-demultiplexing-of-iSeq-runs`
1. cd cd /home/hiseq.clinical/SCRIPTS/git/demultiplexing/
1. git pull
1. git checkout Automatic-demultiplexing-of-iSeq-runs
1. activate stage: source activate stage
1. cd /home/hiseq.clinical/SCRIPTS/git/demultiplexing/scripts/iseq/

**How to test demultiplexing**:
1. run following command: ` bash demux-iseq.bash /home/hiseq.clinical/iseq/runs/20190528_FS10000534_7_BPC29611-3324/ /home/hiseq.clinical/iseq/demux/`

**Expected outcome**:
- [x] demultiplexing should start happily

**How to test checking for new run**:
1. run following command: `bash checkfornewrun.bash /home/hiseq.clinical/iseq/runs/ /home/hiseq.clinical/iseq/demux/`

**Expected outcome**:
- [x] all runs without a `demuxstarted.txt` file should start. All other should be mentioned as already demultiplexed.

Take a screenshot and attach or copy/paste the output.

**Review:**
- [x] code approved by @ingkebil @barrystokman 
- [x] tests executed by @patrikgrenfeldt @emiliaol tested in cgstats iseq [PR ](https://github.com/Clinical-Genomics/cgstats/pull/21)
- [x] "Merge and deploy" approved by @ingkebil 
Thanks for filling in who performed the code review and the test!

This is |minor| **version bump** because we add func without altering the old one

### CODE REVIEW

**Comment by patrikgrenfeldt** [comment]
Test result:
image

👎

**Comment by patrikgrenfeldt** [comment]
Test result demux: 
image

👍

**Comment by patrikgrenfeldt** [comment]
Test result check for new demux:
image

👍

**Comment by ingkebil** [comment]
put both files through a linter :)

**Comment by ingkebil** [comment]
Code looks good! Feel free to approve in my name when tests are completed and the version bump is motivated

**Comment by ingkebil** [comment]
Approving M&D :rocket:

**Comment by patrikgrenfeldt** [comment]
did you check the output as in did you check if the fastq files are named properly?

**Comment by patrikgrenfeldt** [comment]
> Just wondering as this is also renaming the fastq files, did you check if the fastq filenames were sane?

No we did not. What should the names be? How do we know they are correct?

**Comment by ingkebil** [comment]
eeh, let's just leave the code in for now. I'm unsure if cgstats is using the restructured dir or not.

**Comment by ingkebil** [comment]
deployed

**Pull request merged**
