### PR TITLE
Fix/lane count novaseq

### PR DESCRIPTION
**Pull request by karlnyr**
Lane counts for all variants of different NovaSeq flowcells. Also, cleaning up the .idea folder present in the repo.

**How to prepare for test**:
- [ ] ssh to hasta
- [ ] install on stage:
`bash servers/resources/hasta.scilifelab.se/update-demux-stage.sh fix/lane-count-novaseq`

**How to test**:
- [ ] login to hasta
- [ ] `demux indexreport summary ....` on a SP flowcell: HYK5VDRXX

**Expected test outcome**:
- [ ] A summary report is created
- [ ] Take a screenshot and attach or copy/paste the output.

**Review:**
- [ ] code approved by
- [ ] tests executed by @karlnyr 
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by karlnyr** [comment]
Installing on stage:
image

Running on SP flowcell:
image

**Review by barrystokman — APPROVED** [review]
👍🏻 

A nice test or even a unit test would be the icing on the 🍰

**Comment by karlnyr** [comment]
@barrystokman your will is my command

**Comment by karlnyr** [comment]
Installing on stage again:
image

Running on a SP flowcell:
image

**Comment by karlnyr** [comment]
Installed on prod:
image

**Pull request merged**
