### PR TITLE
Add autocreate basemask based on runParameters.xml

### PR DESCRIPTION
**Pull request by ingkebil**
Some bash magic to autocreate a basemask based on the RunParameters instead of us having to try to figure out what it is all about.

### CODE REVIEW

**Comment by mayabrandi** [comment]
I would have dont this in python, otherwise I have no comments :) To long since I read bash code..

**Comment by robinandeer** [comment]
Yeah I'm a bit lost but I trust you and this isn't supercritical but very nice indeed! 😉

**Comment by ingkebil** [comment]
Not supercritical? :o

But ok, this code sure could benefit from a rewrite. To be honest, the automatic basemask creation is something I adapted from the same script for the Xs and which has been in productuion without problems for over a year.

**Comment by robinandeer** [comment]
I meant we would pick this up if it behaved weirdly, no?

Good for now!

**Comment by ingkebil** [comment]
The basemask when set to bigger than what `bcl2fastq` would encounter (in the BCL files I presume) in terms of read and index length, then it will yield an error and exit.
It will run if the index is set to something smaller than the length of the index and this will not be detected easily except by Emma Eagle-Eyes.

In any case, this code should improve how one demux's FCs with mixed length indexes by simply changing the samplesheet and rerunning. No need to set any params anymore (albeit, it is still possible).

I need to validate anyway.

Ok to merge?

**Comment by b4ckm4n** [comment]
OK to merge

**Pull request merged**
